import type { AgentProvider } from '../../shared/types';
import type { AgentNameSequence } from './tokens';

export const CLAUDE_NAME_SEQUENCE: ReadonlyArray<string> = [
  'Antoine',
  'Baptiste',
  'Dominique',
  'Éloise',
  'François',
  'Guillaume',
  'Hélène',
  'Isabelle',
  'Jacques',
  'Karine',
  'Luc',
  'Marcel',
  'Noémie',
  'Olivier',
  'Pierre',
  'Quentin',
  'Renée',
  'Sophie',
  'Théo',
  'Ulysse',
  'Valérie',
  'William',
  'Xavier',
  'Yves',
  'Zoé',
];

export const CODEX_NAME_SEQUENCE: ReadonlyArray<string> = [
  'Aiden',
  'Bianca',
  'Darius',
  'Evelyn',
  'Felix',
  'Gabriel',
  'Hazel',
  'Iris',
  'Jasper',
  'Keira',
  'Liam',
  'Maya',
  'Noah',
  'Olive',
  'Preston',
  'Quinn',
  'Rowan',
  'Sienna',
  'Theo',
  'Uma',
  'Victor',
  'Willow',
  'Xander',
  'Yara',
  'Zane',
];

export const DEFAULT_AGENT_NAME_SEQUENCES: Record<AgentProvider, AgentNameSequence> = {
  claude: { first: 'Claude', sequence: CLAUDE_NAME_SEQUENCE },
  codex: { first: 'Codex', sequence: CODEX_NAME_SEQUENCE },
  cursor: { first: 'Cursor', sequence: CODEX_NAME_SEQUENCE },
};
